### ISSUE TITLE
Which pytorch is using for this repo?

### ISSUE THREAD

**Issue by leiwen83** [netx-repo/PipeSwitch#2]
I try run the pipeswitch section, but meet below error:
python main.py model_list.txt
TIMESTAMP, frontend, start, 1608555799.825023
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 24, in main
    torch.cuda.allocate_shared_cache()
AttributeError: module 'torch.cuda' has no attribute 'allocate_shared_cache'

So which torch version shall I use to fix it?

Thx,
Lei

**Comment by juinshell** [comment]
I have the same problem, how did you solve it in the end?
